# Generated by Django 4.2.28 on 2026-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('join_request', 'Join Request'), ('join_request_accepted', 'Join Request Accepted'), ('join_request_rejected', 'Join Request Rejected'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('mention', 'Mention'), ('announcement', 'Announcement'), ('deadline_reminder', 'Deadline Reminder'), ('feedback', 'Feedback Received'), ('system', 'System Notification')], max_length=50)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_join_requests', models.BooleanField(default=True)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_completed', models.BooleanField(default=True)),
                ('email_mentions', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_deadline_reminders', models.BooleanField(default=True)),
                ('email_feedback', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=False)),
                ('push_join_requests', models.BooleanField(default=True)),
                ('push_task_assigned', models.BooleanField(default=True)),
                ('push_task_completed', models.BooleanField(default=True)),
                ('push_mentions', models.BooleanField(default=True)),
                ('push_announcements', models.BooleanField(default=True)),
                ('push_deadline_reminders', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
