# Generated by Django 6.0.3 on 2026-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_github_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_skill'),
        ),
    ]
