# Generated by Django 6.0.3 on 2026-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userskill_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='Your GitHub username (validated against GitHub)', max_length=39, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'name')},
        ),
    ]
