# Generated by Django 4.2.28 on 2026-02-26 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_preference', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('mentor', 'Mentor'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField(help_text='Mandatory: What problem does this project solve?')),
                ('category', models.CharField(choices=[('ai', 'Artificial Intelligence'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ml', 'Machine Learning'), ('data', 'Data Science'), ('devops', 'DevOps'), ('blockchain', 'Blockchain'), ('game', 'Game Development'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='intermediate', max_length=20)),
                ('max_team_size', models.IntegerField(default=5)),
                ('required_roles', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('estimated_duration', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', max_length=10)),
                ('status', models.CharField(choices=[('idea', 'Idea Stage'), ('accepting', 'Accepting Members'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='idea', max_length=20)),
                ('is_beginner_friendly', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('health_status', models.CharField(choices=[('active', 'Active'), ('slow', 'Slow'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('mentor', 'Mentor'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('mentor', 'Mentor'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='projects.project')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
