# Generated by Django 4.2.28 on 2026-02-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='projects.project'),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_integration.githubrepository'),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='github_integration.githubrepository'),
        ),
    ]
