# Generated by Django 4.2.28 on 2026-02-26 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('github_integration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='githubcommit',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_integration.githubrepository'),
        ),
        migrations.AddField(
            model_name='contributionanalytics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_analytics', to='projects.project'),
        ),
        migrations.AddField(
            model_name='contributionanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='githubpullrequest',
            unique_together={('repository', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='githubissue',
            unique_together={('repository', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='githubcommit',
            unique_together={('repository', 'sha')},
        ),
        migrations.AlterUniqueTogether(
            name='contributionanalytics',
            unique_together={('user', 'project')},
        ),
    ]
